theme: jekyll-theme-minimal

title: RainLeander.GitHub.io # The title of your website, as you want it to appear in the header of the webpage.
email: rainsdance [at] gmail [dot] com # Your email address.
description: A GroningenRain.nl Experiment
baseurl: /
twitter_username: rainleander
github_username: rainleander
